load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "clover_demo",
    srcs = [
        "main.cc",
    ],
    deps = [
        "//backend",
        "@absl//absl/status",
        "@fmt",
    ],
)
